title: Minimal Jekyll Blog
author: Agustín Vázquez Cendron
email: agustiki@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning Github Pages with Jekyll.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  avazquezcendron # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
